/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  // this is basically just an example of how you can work with unit tests
   /*  @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }*/
}
